name: flutter_google_map_route
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  location: ^2.5.4
#  map_view: ^0.0.14
  cirrus_map_view: ^1.0.0
  google_maps_webservice: ^0.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


